# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui_files/ventana_principal_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 812)
        MainWindow.setStyleSheet("    QMainWindow {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(32, 56, 92, 255), stop:1 rgba(4, 89, 209, 255));\n"
"        color: #333;\n"
"    }\n"
"\n"
"    QPushButton {\n"
"        background-color: #0C60DB;\n"
"        color: white;\n"
"        border: none;\n"
"        padding: 10px 20px;\n"
"        text-align: center;\n"
"        text-decoration: none;\n"
"        font-size: 14px;\n"
"        margin: 4px 2px;\n"
"        border-radius: 8px;\n"
"    }\n"
"\n"
"    QComboBox {\n"
"        background-color: #0C60DB;\n"
"        color: white;\n"
"        border: none;\n"
"        padding: 10px 20px;\n"
"        text-align: center;\n"
"        text-decoration: none;\n"
"        font-size: 14px;\n"
"        margin: 4px 2px;\n"
"        border-radius: 8px;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: #0354CA;\n"
"    }\n"
"\n"
"    QCheckBox {\n"
"        font-size: 18px;\n"
"        color: white\n"
"    }\n"
"\n"
"    QCheckBox::indicator {\n"
"        width: 20px;\n"
"        height: 20px;\n"
"    }\n"
"\n"
"\n"
"    QDateEdit {\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        padding: 5px;\n"
"        background: white;\n"
"    }\n"
"\n"
"    QDateEdit::drop-down {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 15px;\n"
"        border-left-width: 1px;\n"
"        border-left-color: darkgray;\n"
"        border-left-style: solid;\n"
"        border-top-right-radius: 3px;\n"
"        border-bottom-right-radius: 3px;\n"
"    }\n"
"\n"
"\n"
"    QLineEdit, QLabel {\n"
"        font-size: 14px;\n"
"        color: #333;\n"
"    }\n"
"\n"
"    QPushButton#openFileButton {\n"
"        background-color: #2196F3;\n"
"        color: white;\n"
"    }\n"
"\n"
"    QPushButton#openFileButton:hover {\n"
"        background-color: #0b7dda;\n"
"    }\n"
"\n"
"    QLabel {\n"
"        color: white;\n"
"    }\n"
"\n"
"    #selectedfile, #selectedfile_2, #selectedfile_3 {\n"
"        font-size: 20px\n"
"    }\n"
"\n"
"    #label_2 {\n"
"        font-size:18px\n"
"    }\n"
"      #label_3 {\n"
"        font-size:18px\n"
"    }\n"
"    QProgressBar {\n"
"        color: white;\n"
"        font-size: 18px;\n"
"    }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.initialdate = QtWidgets.QDateEdit(self.centralwidget)
        self.initialdate.setGeometry(QtCore.QRect(430, 280, 131, 41))
        self.initialdate.setObjectName("initialdate")
        self.enddate = QtWidgets.QDateEdit(self.centralwidget)
        self.enddate.setGeometry(QtCore.QRect(610, 280, 121, 41))
        self.enddate.setObjectName("enddate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 230, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 230, 111, 31))
        self.label_3.setObjectName("label_3")
        self.openfilebtn = QtWidgets.QPushButton(self.centralwidget)
        self.openfilebtn.setGeometry(QtCore.QRect(400, 360, 121, 61))
        self.openfilebtn.setObjectName("openfilebtn")
        self.selectedfile = QtWidgets.QLabel(self.centralwidget)
        self.selectedfile.setGeometry(QtCore.QRect(540, 360, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.selectedfile.setFont(font)
        self.selectedfile.setStyleSheet("")
        self.selectedfile.setObjectName("selectedfile")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(840, 270, 181, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 110, 1076, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.double_top = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.double_top.setObjectName("double_top")
        self.horizontalLayout.addWidget(self.double_top)
        self.double_bottom = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.double_bottom.setObjectName("double_bottom")
        self.horizontalLayout.addWidget(self.double_bottom)
        self.head_and_shoulders = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.head_and_shoulders.setObjectName("head_and_shoulders")
        self.horizontalLayout.addWidget(self.head_and_shoulders)
        self.inv_head_and_shoulders = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.inv_head_and_shoulders.setObjectName("inv_head_and_shoulders")
        self.horizontalLayout.addWidget(self.inv_head_and_shoulders)
        self.descending_triangle = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.descending_triangle.setObjectName("descending_triangle")
        self.horizontalLayout.addWidget(self.descending_triangle)
        self.ascending_triangle = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.ascending_triangle.setObjectName("ascending_triangle")
        self.horizontalLayout.addWidget(self.ascending_triangle)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(400, 680, 421, 51))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.historicpatternsbtn_both = QtWidgets.QPushButton(self.centralwidget)
        self.historicpatternsbtn_both.setGeometry(QtCore.QRect(350, 520, 221, 61))
        self.historicpatternsbtn_both.setObjectName("historicpatternsbtn_both")
        self.currentpatternsbtn_both = QtWidgets.QPushButton(self.centralwidget)
        self.currentpatternsbtn_both.setGeometry(QtCore.QRect(610, 520, 221, 61))
        self.currentpatternsbtn_both.setObjectName("currentpatternsbtn_both")
        self.h_search_type = QtWidgets.QComboBox(self.centralwidget)
        self.h_search_type.setGeometry(QtCore.QRect(490, 600, 221, 51))
        self.h_search_type.setObjectName("h_search_type")
        self.h_search_type.addItem("")
        self.h_search_type.addItem("")
        self.h_search_type.addItem("")
        self.selectedfile_2 = QtWidgets.QLabel(self.centralwidget)
        self.selectedfile_2.setGeometry(QtCore.QRect(360, 590, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.selectedfile_2.setFont(font)
        self.selectedfile_2.setStyleSheet("")
        self.selectedfile_2.setObjectName("selectedfile_2")
        self.selectedfile_3 = QtWidgets.QLabel(self.centralwidget)
        self.selectedfile_3.setGeometry(QtCore.QRect(880, 220, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.selectedfile_3.setFont(font)
        self.selectedfile_3.setStyleSheet("")
        self.selectedfile_3.setObjectName("selectedfile_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1206, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Initial date"))
        self.label_3.setText(_translate("MainWindow", "End date"))
        self.openfilebtn.setText(_translate("MainWindow", "Open File"))
        self.selectedfile.setText(_translate("MainWindow", "Selected file: None"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Normal Search"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Fast Search"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Deep Search"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Very Deep Search"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Small Patterns Search"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Big Patterns Search"))
        self.double_top.setText(_translate("MainWindow", "Double top"))
        self.double_bottom.setText(_translate("MainWindow", "Double bottom"))
        self.head_and_shoulders.setText(_translate("MainWindow", "Head and shoulders"))
        self.inv_head_and_shoulders.setText(_translate("MainWindow", "Inverse head and shoulders"))
        self.descending_triangle.setText(_translate("MainWindow", "Descending triangle"))
        self.ascending_triangle.setText(_translate("MainWindow", "Ascending triangle"))
        self.historicpatternsbtn_both.setText(_translate("MainWindow", "Search historic patterns"))
        self.currentpatternsbtn_both.setText(_translate("MainWindow", "Search current patterns"))
        self.h_search_type.setItemText(0, _translate("MainWindow", "DTW and Neural Network"))
        self.h_search_type.setItemText(1, _translate("MainWindow", "DTW"))
        self.h_search_type.setItemText(2, _translate("MainWindow", "Neural Network"))
        self.selectedfile_2.setText(_translate("MainWindow", "Search mode"))
        self.selectedfile_3.setText(_translate("MainWindow", "Search type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
